### ISSUE TITLE
support incomplete CAR files

### ISSUE THREAD

**Issue by mikeal** [nftstorage/carbites#10]
Currently, carbites will fail on parsing an incomplete CAR file as input, in looking for blocks that aren’t in it. This means incomplete CAR files error in the web3.storage client.

I unblocked a user by directing them to the REST API for car uploads but it would be nice if carbites just skipped traversal over blocks that’s aren’t in the input CAR file.

**Comment by alanshaw** [comment]
If a CAR has already been split using the treewalk strategy this seems reasonable...but there's no way of knowing this. If it's just a CAR of random blocks then carbites would end up skipping everything which would be bad!

Ideally we wouldn't walk the tree at all because it makes assumptions about how the DAG was constructed (i.e. dag-pb/cbor/raw only). I opened [an issue](https://github.com/nftstorage/nft.storage/issues/821) about this a while ago TLDR; if we're given a CAR we should just be able to use the simple strategy to ensure it doesn't exceed the cloudflare request limit. This is really a change for the client library though, not a change here.
