### ISSUE TITLE
Exception: Cannot find module 'carbites/treewalk'

### ISSUE THREAD

**Issue by naftalimurgor** [nftstorage/carbites#9]
Os: Ubuntu 16.0.4
Nodejs version: 14.0.0

Desired behavior: I'm looking to uploading some `NFT` images using `nft.storage` client library from Nodejs. 
What I have done:
```javascript
// some code omitted
const uploadImageToIPFS = async (
  path,
  name,
) => {
  const API_TOKEN = process.env.API_TOKEN
  const client = new NFTStorage({ token: API_TOKEN })
  try {

    const file = fs.promises.readFile(path)
    const metadata = await client.store({
      name: 'Maasai Morans',
      description: `Hello, all the from Maasai Mara. Here come the morans`,
      image: new File(
        [file],
        `${name}.jpg`,
        { type: 'image/jpg' }
      ),
    })

    console.log(metadata)
    return {
      url: metadata.url,
      ipnft: metadata.ipnft,
      ipfsImage: metadata.data.image.href,
      hostedImage: metadata.embed().image.href
    }

  } catch (ex) {
    console.log(ex)
  }
}
```
Output: 
```javascript
events.js:292
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer. Received an instance of Uint8Array
    at write_ (_http_outgoing.js:679:11)
    at ClientRequest.write (_http_outgoing.js:644:15)
    at Readable.ondata (_stream_readable.js:707:22)
    at Readable.emit (events.js:315:20)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Readable.push (_stream_readable.js:213:10)
    at next (internal/streams/from.js:51:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (internal/streams/destroy.js:96:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
Output: (Stepping through the code using a debuger):
`Process exited with code 1
Uncaught Error: Cannot find module 'carbites/treewalk`
I can't seem to get this work. Any kind of help is highly appreciated.

Thank you

**Comment by jakerainis** [comment]
My team is also running into this issue as well (node@16), which I believe is because `carbites` is an ESM-only library. Our build can't resolve the module.

**Comment by naftalimurgor** [comment]
@jakerainis At first I thought it was a problem a problem with Nodejs version. Has your team been able to upload the NFT artifacts using any other means? I'm looking to upload over 1200 images but can't seem to wrap my head around this issue yet.

**Comment by jakerainis** [comment]
@naftalimurgor Yeah, it was puzzling to me as well. In any case, I was able to find a workaround and hopefully this works for you as well. Instead of using this library, I've removed it an am now just using the [NFT Storage API](https://nft.storage/api-docs/). Before, I was doing something like this:

```js
const cid = await client.storeBlob(new Blob([file]))
```

Now I'm doing this:
```js
const { body } = await got.post('https://api.nft.storage/upload', {
      headers: { Authorization: `Bearer ${YOUR_API_KEY}` },
      body: file,
})
const cid = JSON.parse(body).value.cid
```

Note: I'm using [got](https://www.npmjs.com/package/got) as my HTTP library, but you can use node-fetch, Axios, or whatever http tooling you prefer.

Hope this helps!

**Comment by naftalimurgor** [comment]
Wow, thanks for the insight. Let me try to using that approach. Will let you know in case of any issues.

**Comment by alanshaw** [comment]
In other cases we've found the problem to be because the library is being bundled with webpack 4.

Webpack 4 does not support [`package.json` `exports`](https://github.com/nftstorage/carbites/blob/d1ca1f91de341f096165452bcfc2b82d169abe3f/package.json#L51) field so is unable to resolve the dependency.

If you can't upgrade to webpack 5, you can use the prebuilt library:

```js
import { NFTStorage } from 'nft.storage/dist/bundle.esm.min.js'
```
